package date.liyin.vly.virtualrender

enum class PlaceMode {
    HORIZONTAL_UPWARD_ONLY, VERTICAL_ONLY, HORIZONTAL_UPWARD_AND_VERTICAL_DIRECT, HORIZONTAL_UPWARD_AND_VERTICAL_ROTATE, VERTICAL_ONLY_ROTATE
}